title: Charlie Crisp's Website
email: charliecrisp249@gmail.com
description: >-
  This is a personal website all about me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://charliecrisp.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  charliecrisp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: ./sass
  style: :compressed
