routes:
  - name: Education
    url: /education
    icon_url: cambridgeicon.png
    color:
      x: 91
      y: 159
      z: 148
  - name: Positions
    url: /positions
    icon_url: hcicon.png
    color:
      x: 150
      y: 82
      z: 138
  - name: Blogs/Workshops
    url: /blogs
    icon_url: blogstile.png
    color:
        x: 83
        y: 144
        z: 78
  - name: Projects
    url: projects
    icon_url: wvlogo.png
    color:
      x: 58
      y: 95
      z: 114