- name: Education
  url: /education
- name: Positions
  url: /positions
- name: Projects
  url: /projects
- name: Blogs/Workshops
  url: /blogs
- name: CV
  url: /cv.pdf
- name: Github
  url: https://github.com/charliecrisp
  icon_class: fa-github
- name: LinkedIn
  url: https://www.linkedin.com/in/charlie-crisp-88aab5122/
  icon_class: fa-linkedin-square